### ISSUE TITLE
Centos 6, 64. Can't install.

### ISSUE THREAD

**Issue by shaoyingrui** [frjalex/oneclickVPN#1]
pptpd           [ Failed ]
openvpn         [ Failed ]
ipsec           [ Failed ]
xl2tpd          [ OK ]
sed: can't read /etc/openvpn/radiusplugin.cnf: No such file or directory
sed: can't read /etc/openvpn/radiusplugin.cnf: No such file or directory
sed: can't read /usr/local/etc/radiusclient/radiusclient.conf: No such file or directory
sed: can't read /usr/local/etc/radiusclient/radiusclient.conf: No such file or directory
mv: cannot stat `/usr/local/etc/radiusclient/servers': No such file or directory
vpn4in1.sh: line 628: /usr/local/etc/radiusclient/servers: No such file or directory
# Please in your freeradius server execute the following command

iptables -A INPUT -i eth0 -p udp -s 107.191.53.112 --dport 1812 -j ACCEPT
iptables -A INPUT -i eth0 -p udp -s 107.191.53.112 --dport 1813 -j ACCEPT
cat >> /etc/raddb/clients.conf <<EOF
client localhost {
        ipaddr = 107.191.53.112
        secret = cefhost
        require_message_authenticator = no
        nastype     = other
}
EOF

**Comment by frjalex** [comment]
The OpenVpn radius client and the radiusclient seems to be not installed. This script has long since maintained. I recommend you this, if you really need some kind of script to deploy a usable VPN server: http://frjalex.github.io/useful
